version: "3.5"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_service
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: apache_kafka_service
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 3  # Default number of partitions
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1 # Default replication factor

