version: "3.5"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_service
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper  # Data persistence
    environment:
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka
    container_name: apache_kafka_service
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # Enable auto creation of topics
      KAFKA_LOG_RETENTION_HOURS: 168           # Keep logs for 7 days
    volumes:
      - kafka_data:/var/lib/kafka/data  # Data persistence
    networks:
      - kafka_network

volumes:
  zookeeper_data:
  kafka_data:

networks:
  kafka_network:


# Docker environment values for ref which we can use it
#environment:
#  KAFKA_ADVERTISED_HOST_NAME: localhost
#  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#  KAFKA_LOG_RETENTION_HOURS: 168
#  KAFKA_LOG_RETENTION_BYTES: 1073741824  # 1 GB
#  KAFKA_DEFAULT_REPLICATION_FACTOR: 1    # Default replication factor
#  KAFKA_NUM_PARTITIONS: 3                # Default number of partitions