version: "3.5"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_service
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  kafka:
    image: wurstmeister/kafka
    container_name: apache_kafka_service
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  create_topics:
    image: wurstmeister/kafka
    container_name: kafka_topic_creator
    depends_on:
      - kafka
    entrypoint: >
      sh -c "kafka-topics.sh --create --topic my_custom_topic --zookeeper zookeeper:2181 --partitions 3 --replication-factor 2;
      while true; do sleep 1000; done"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
