spring:
  cloud:
    gateway:
      routes:
        - id: order-microservice
          uri: lb://ORDER-MICROSERVICE
          predicates:
            - Path=/orders/**
        - id: payment-microservice
          uri: lb://PAYMENT-MICROSERVICE
          predicates:
            - Path=/payments/**
        - id: user-microservice
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/users/**
        - id: auth-microservice
          uri: lb://AUTH-MICROSERVICE
          predicates:
            - Path=/auth/**
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/